apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: poct
type: application
version: 0.1.0

dependencies:
  - name: mysql
    version: 14.0.3
    repository: "https://charts.bitnami.com/bitnami"
   
