apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: POCT-pvc
  namespace: argoPOCT
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-rbd