{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Skip
  name: {{ include "poct.fullname" . }}-secret
spec:
  encryptedData:
    API_KEY: {{ .Values.secrets.API_KEY }}
    DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD }}
    FOO_SECRET: {{ .Values.secrets.FOO_SECRET }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        sealedsecrets.bitnami.com/managed: "true"
      name: {{ include "poct.fullname" . }}-secret
    type: Opaque
{{- end }}
