apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-app
  namespace: argotest
spec:
  project: default
  source:
    repoURL: 'https://github.com/mmostofian/ArgoCD.git' 
    targetRevision: HEAD
    path: manifests  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argotest 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
