{{- if .Values.sealedSecretsController.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "sealed-secrets-controller" .Values.sealedSecretsController.nameOverride }}
  namespace: {{ .Values.sealedSecretsController.namespace }}
{{- end }}


