
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealed-secrets-controller
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sealed-secrets-controller
subjects:
- kind: ServiceAccount
  name: sealed-secrets-controller
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: sealed-secrets-controller
  apiGroup: rbac.authorization.k8s.io
