apiVersion: v2
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
spec:
  containers:
    - name: {{ .Values.pod.name }}
      image: {{ .Values.pod.image }}
      ports:
        - containerPort: {{ .Values.pod.port }}
