apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: poct
type: application
version: 0.1.0

dependencies:
- name: redis
  condition: redis.enabled
  version: 18.19.4   
  repository: https://charts.bitnami.com/bitnami
    
