apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: poct
type: application
version: 0.1.0

dependencies:
- name: redis
  condition: redis.enabled
  version: 8.0.6-8
  repository: https://helm.redis.io
    
