apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mmostofian/ArgoCD.git
    path: sealed-secrets-app
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
