apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
spec:
  containers:
    - name: my-container
      image: {{ .Values.pod.image }}
      ports:
        - containerPort: {{ .pod.port }}